//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airline1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_flight
    {
        public string flight_id { get; set; }
        public string flight_name { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string arrival_time { get; set; }
        public string departure { get; set; }
        public string flight_class { get; set; }
        public Nullable<decimal> flight_charges { get; set; }
        public Nullable<int> seats { get; set; }
    }
}
