//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airline1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public string message_id { get; set; }
        public string pengirim { get; set; }
        public string penerima { get; set; }
        public string message { get; set; }
        public string subject { get; set; }
    }
}
