//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airline1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_booking
    {
        public string ticket_id { get; set; }
        public string costumer_id { get; set; }
        public Nullable<System.DateTime> dateofjourney { get; set; }
        public string flight_id { get; set; }
        public Nullable<int> seat_no { get; set; }
    }
}
